spring:
  application:
    name: suggestion-service

server:
  error:
    include-message: always

ws:
  endpoint: suggestions
  file:
    path: /home/joel/Downloads/backend-coding-challenge-one-master/data/cities_canada-usa.tsv